module load sratoolkit/2.8.2-1
module load trimmomatic
module load bowtie/1.0.0
module load bowtie2/2.3.2
module load blat
module load perl
module load R
module load samtools
module load bedtools/2.17.0
module load sambamba
module load controlfreec
module load python/2.7.13
module load cutadapt 